// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Text to be analyzed and requested analysis methods. if not specified all analyses are executed.
 * @export
 * @interface AnalyzeRequest
 */
export interface AnalyzeRequest {
    /**
     * Up to 200kb of UTF-8 encoded raw text to be analyzed. The language is detected automatically and it should be one of the following: English (en), French (fr), German (de), Italian (it), Japanese (ja), Korean (ko), Portuguese (pt), Russian (ru), Spanish (es)
     * @type {string}
     * @memberof AnalyzeRequest
     */
    text: string;
    /**
     * Extractors detect spans in the text and return their normalized description.
     * @type {Array<string>}
     * @memberof AnalyzeRequest
     */
    extractors?: Array<AnalyzeRequestExtractorsEnum>;
    /**
     * Only return extractors results with score above the threshold between 0 and 1. if not specified return all results.
     * @type {number}
     * @memberof AnalyzeRequest
     */
    extractorsScoreThreshold?: number;
    /**
     * Classifiers categorize the whole text according to industry standard taxonomies.
     * @type {Array<string>}
     * @memberof AnalyzeRequest
     */
    classifiers?: Array<AnalyzeRequestClassifiersEnum>;
    /**
     * Only return categories with score above the threshold between 0 and 1. if not specified return all detected categories.
     * @type {number}
     * @memberof AnalyzeRequest
     */
    classifierScoreThreshold?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum AnalyzeRequestExtractorsEnum {
    Entities = 'entities',
    Topics = 'topics'
}
/**
    * @export
    * @enum {string}
    */
export enum AnalyzeRequestClassifiersEnum {
    IPTCNewsCodes = 'IPTCNewsCodes',
    IPTCMediaTopics = 'IPTCMediaTopics',
    IABTaxonomy = 'IABTaxonomy'
}



