// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClassifierCategory
 */
export interface ClassifierCategory {
    /**
     * 
     * @type {string}
     * @memberof ClassifierCategory
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCategory
     */
    classifierId?: ClassifierCategoryClassifierIdEnum;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCategory
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCategory
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassifierCategory
     */
    score?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ClassifierCategoryClassifierIdEnum {
    IPTCNewsCodes = 'IPTCNewsCodes',
    IPTCMediaTopics = 'IPTCMediaTopics',
    IABTaxonomy = 'IABTaxonomy'
}



