// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KnowledgeGraph } from './knowledge-graph';

/**
 * 
 * @export
 * @interface KnowledgeGraphSearchResponseItems
 */
export interface KnowledgeGraphSearchResponseItems {
    /**
     * An indicator of how well the entity matched the request constraints.
     * @type {number}
     * @memberof KnowledgeGraphSearchResponseItems
     */
    resultScore?: number;
    /**
     * 
     * @type {KnowledgeGraph}
     * @memberof KnowledgeGraphSearchResponseItems
     */
    result?: KnowledgeGraph;
}


