// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An image to help identify the entity.
 * @export
 * @interface KnowledgeGraphImage
 */
export interface KnowledgeGraphImage {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeGraphImage
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeGraphImage
     */
    contentUrl?: string;
}


