// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KnowledgeGraphDetailedDescription } from './knowledge-graph-detailed-description';
import { KnowledgeGraphImage } from './knowledge-graph-image';

/**
 * 
 * @export
 * @interface KnowledgeGraph
 */
export interface KnowledgeGraph {
    /**
     * Google knowledge graph id.
     * @type {string}
     * @memberof KnowledgeGraph
     */
    mid?: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeGraph
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KnowledgeGraph
     */
    types?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeGraph
     */
    description?: string;
    /**
     * 
     * @type {KnowledgeGraphDetailedDescription}
     * @memberof KnowledgeGraph
     */
    detailedDescription?: KnowledgeGraphDetailedDescription;
    /**
     * 
     * @type {KnowledgeGraphImage}
     * @memberof KnowledgeGraph
     */
    image?: KnowledgeGraphImage;
    /**
     * The official website URL of the entity, if available.
     * @type {string}
     * @memberof KnowledgeGraph
     */
    url?: string;
}


