// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KnowledgeGraphSearchResponseItems } from './knowledge-graph-search-response-items';

/**
 * 
 * @export
 * @interface KnowledgeGraphSearchResponse
 */
export interface KnowledgeGraphSearchResponse {
    /**
     * 
     * @type {Array<KnowledgeGraphSearchResponseItems>}
     * @memberof KnowledgeGraphSearchResponse
     */
    items: Array<KnowledgeGraphSearchResponseItems>;
}


