// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Generic description of a file location according to the EBU FIMS specification.
 * @export
 * @interface Locator
 */
export interface Locator {
    /**
     * Name of an AWS S3 bucket
     * @type {string}
     * @memberof Locator
     */
    awsS3Bucket: string;
    /**
     * Name of a file in the AWS S3 bucket. For example, name of media file to be indexed in an Input Locator or name of a JSON file in an Output Locator.
     * @type {string}
     * @memberof Locator
     */
    awsS3Key: string;
    /**
     * Public URL to access the file in the bucket. Must be computed using the AWS SDK method `GeneratePresignedUrl`
     * @type {string}
     * @memberof Locator
     */
    httpEndpoint: string;
}


