// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Locator } from './locator';
import { SegmentTextResponse } from './segment-text-response';

/**
 * 
 * @export
 * @interface SegmentTextRequest
 */
export interface SegmentTextRequest {
    /**
     * 
     * @type {Locator}
     * @memberof SegmentTextRequest
     */
    inputFile: Locator;
    /**
     * 
     * @type {SegmentTextResponse}
     * @memberof SegmentTextRequest
     */
    outputLocation: SegmentTextResponse;
    /**
     * 
     * @type {number}
     * @memberof SegmentTextRequest
     */
    lines?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentTextRequest
     */
    characters?: number;
}


