// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Span
 */
export interface Span {
    /**
     * 
     * @type {string}
     * @memberof Span
     */
    content?: string;
    /**
     * The API calculates the beginning offset of the content in the original document as a number of characters starting from zero index position.
     * @type {number}
     * @memberof Span
     */
    beginOffset?: number;
}


