// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    label?: string;
    /**
     * Link to Wikipedia for this topic, or None if this topic couldn\'t be linked to a Wikipedia page.
     * @type {string}
     * @memberof Topic
     */
    wikiLink?: string;
    /**
     * The relevance of this topic to the processed document. This score ranges from 0 to 1, with 1 representing the highest relevance of the topic to the processed document.
     * @type {number}
     * @memberof Topic
     */
    score?: number;
    /**
     * The disambiguated Wikidata QID for this topic, or None if either this topic could not be disambiguated, or a Wikidata link doesn’t exist.
     * @type {string}
     * @memberof Topic
     */
    wikidataId?: string;
}


