// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Locator } from './locator';
import { TranslateCaptionsResponse } from './translate-captions-response';

/**
 * 
 * @export
 * @interface TranslateCaptionsRequest
 */
export interface TranslateCaptionsRequest {
    /**
     * 
     * @type {Locator}
     * @memberof TranslateCaptionsRequest
     */
    sourceSubtitle: Locator;
    /**
     * 
     * @type {TranslateCaptionsResponse}
     * @memberof TranslateCaptionsRequest
     */
    outputLocation: TranslateCaptionsResponse;
    /**
     * 
     * @type {string}
     * @memberof TranslateCaptionsRequest
     */
    targetLanguage: string;
    /**
     * 
     * @type {boolean}
     * @memberof TranslateCaptionsRequest
     */
    skeletonMode: boolean;
    /**
     * 
     * @type {string}
     * @memberof TranslateCaptionsRequest
     */
    sourceLanguage?: string;
}


