// tslint:disable
/**
 * Dalet Metadata Analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: cortexsupport@dalet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TranslateTextResponse
 */
export interface TranslateTextResponse {
    /**
     * The source language that was detected by the API in case it was not specified in the request.
     * @type {string}
     * @memberof TranslateTextResponse
     */
    detectedSourceLanguage?: string;
    /**
     * Translated text.
     * @type {string}
     * @memberof TranslateTextResponse
     */
    text: string;
}


